version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3000:3000
    depends_on:
      - db
    command: sh -c "npx prisma db push && npm run start"

volumes:
  postgres-data:
