services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - HOST_PUBLIC_LINK=<your_base_url>/send-to/
      - DATABASE_URL=postgresql://<db_username>:<db_password>@postgres:5432/ku-xmas
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: <postgres_user>
      POSTGRES_PASSWORD: <postgres_password>
      POSTGRES_DB: ku-xmas
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: